---
- include: get_key.yml

- name: add google key to apt-key
  apt_key: file=/tmp/google.pub

- name: google sources.list
  template:
    src: google-chrome.list.j2
    dest: /etc/apt/sources.list.d/google-chrome.list
    force: no
    mode: 0644
  register: sources_list_result

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed

- name: Install google-chrome
  apt: name=google-chrome-stable
