---
- name: add google key to apt-key
  apt_key: 
    url: "{{ apt_chrome_repo_key }}"
    state: present

- name: APT Chrome Repo
  apt_repository:
    repo: "{{ apt_chrome_repo }}"
    update_cache: yes
    mode: 0644

- name: Install google-chrome
  apt: name=google-chrome-stable
